version: "3.4"
services:

  db:
    container_name: yatest-docker
    image: postgres:13-alpine
    restart: unless-stopped
    ports:
      - 5444:5432
    environment:
      POSTGRES_DB: yatest
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 111
    volumes:
      - ./src/main/resources/database/initDB.sql:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U admin -d yatest" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#      start_period: 10s
#    deploy:
#      resources:
#        limits:
#          cpus: '1'

  ya-test:
    build: ./
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/yatest
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 111
    ports:
      - 80:80
    depends_on:
      - db
