version: "3.4"
services:

  db:
    container_name: yatest-docker
    image: postgres:14.3
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "yatest"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "111"
    volumes:
      - ./src/main/resources/database/initDB.sql:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d yatest" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
